app:
  kafka:
    target-topic: writeBills
    server: financial-tracker-kafka:9092
spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://financial-tracker-postgres-primary:5432/db
    username: ivang
    password: ivang
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres

logging:
  level:
    org.jooq: DEBUG